### ISSUE TITLE
Regarding the implementation of `libmdbx-rs`

### ISSUE THREAD

**Issue by sigridjineth** [SorellaLabs/ethers-reth#3]
Hello, I found that the following binding [implementation](https://github.com/vorot93/libmdbx-rs) seems to be actively maintained since the commits were updated in two weeks ago, as of the time in raising the issue. The repository has been listed officially on the [binding list](https://libmdbx.dqdkfa.ru/usage.html#bindings). I don't know what's the difference between the reth's implementation on libmdbx-rs, which is on the [link](https://github.com/paradigmxyz/reth/tree/7d36dea420c2817e4770e8e23f5ff660404d3e6b/crates/storage/libmdbx-rs).

However, my idea is if there's a repository that actively maintains the binding, it could be better considering the option to utilize it. I want to open up the issue to get some ideas on it.

**Comment by pistomat** [comment]
My understanding is that Reth uses a different implementation because of licensing reasons, they want to use MIT or Apache. Vorotnikov's version (creator of Akula) transitioned to MPL2.0, so they [forked an earlier Apache licensed version](https://github.com/paradigmxyz/reth/blob/main/docs/repo/layout.md#storage) and updated it. 

Lighthouse also uses a fork of an earlier version and [in a comment in Cargo.toml](https://github.com/sigp/lighthouse/blob/c547a11b0da48db6fdd03bca2c6ce2448bbcc3a9/slasher/Cargo.toml#L35) they mention that the latter versions are possibly not compatible with Windows or MacOS.
